steps:
  # Langkah 1: Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/aircraft-backend:$COMMIT_SHA', 
    '-f', 'Dockerfile', # Hapus path 'backend/' karena sudah diatur di GUI
    '.' 
  ]

# Langkah 2: Push Image ke Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/aircraft-backend:$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY